language: node_js
node_js:
  - "8"
before_script:
- travis_retry curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
- export PATH=$HOME/.cargo/bin:$PATH
- travis_retry rustup target add wasm32-unknown-unknown
- cargo install --git https://github.com/alexcrichton/wasm-gc
script:
- npm run rust-sample
- npm test
branches:
  except:
  - staging.tmp
notifications:
  email:
    on_success: never
